### ISSUE TITLE
Variables are not editable when changing pages

### ISSUE THREAD

**Issue by MattTheCuber** [six-two/mkdocs-placeholder-plugin#7] opened 2024-06-05 16:06 UTC
When enabling the `Material for MkDocs` settings for [instant loading](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#instant-loading), switching pages breaks editing.

https://github.com/six-two/mkdocs-placeholder-plugin/assets/32849887/2ca4019d-0dad-4e16-a904-dd703fcbf8d7

*I refreshed to make it work*

This also causes this visual bug at the top of pages that don't use variables:

![chrome_krOJpEwoLu](https://github.com/six-two/mkdocs-placeholder-plugin/assets/32849887/618e914a-57ad-426a-b704-dc8640aac878)

**Comment by six-two** [comment] 2024-06-05 18:13
Thanks for the opening this issue. I have a bit of a backlog of things to do, but I will try to look into it in the coming weeks.

The instant loading bug is caused, because I currently only parse the page when it is loaded. So I would either need to find a hook/event that is called/fired when instant pages are switched or monitor the DOM for changes manually.

I think I have seen the other behavior (with the empty list item) on one of my own pages too. Currently I have no idea why it appears or how to fix it, but I will investigate when I find some time.

**Comment by MattTheCuber** [comment] 2024-06-05 18:34
Great, thank you!

Another thing that would be cool is updating variables without having to hit enter. The automatic placeholder table requires hitting enter, but the manual input field method works without hitting enter (updates on leaving the field I believe). I can provide more info / an example if you want.

**Comment by six-two** [comment] 2024-06-05 18:41
Yes, input fields should update when they loose focus (you tab away or click somewhere else). But placeholder tables (should) just contain normal input fields, like the ones you can add manually. So the behavior you are describing sounds like a bug.

The current main branch (development version) has a lot of changes since the latest release. Does the bug also appear if you use the development version?

**Comment by MattTheCuber** [comment] 2024-06-05 19:14
So, weird thing, it only works on your [live demo](https://mkdocs-placeholder-plugin.six-two.dev/usage/#live-demo).

https://github.com/six-two/mkdocs-placeholder-plugin/assets/32849887/5e1cb8aa-7e73-4993-9163-9d11c64ac4f3

I tried both in the automatic and as a field on it's own and they both didn't work. I also tried the current main branch with the same result.

https://github.com/six-two/mkdocs-placeholder-plugin/assets/32849887/1fb508c4-08af-4bfd-a26a-2ba0f59ed671

Also FYI on main branch as per [this](https://mkdocs-placeholder-plugin.six-two.dev/configuration/#placeholder-settings):

![Code_GLpnAKNBv3](https://github.com/six-two/mkdocs-placeholder-plugin/assets/32849887/95eced2d-4274-453f-85aa-6532cc9c7ab8)

**Comment by six-two** [comment] 2024-06-05 19:27
For now it is fine here, I will review/investigate them later and might move them to their own issue if they are not easily fixed.

But that issue not appearing with my demo page is weird. It is using the same plugin versions that are published. So maybe the issue may be related to your theme / settings? Is your site (and it's source) public, so that I have an easy way to reproduce the issues?

**Comment by six-two** [comment] 2024-06-06 17:34
I think I have fixed the two issues from your initial comment. Instant loading now also updates the page. I suspect it may be a bit buggy, but you can open a new issue if you find any bugs :). The visual glitch seems to be from when the script does not hide the automatically inserted tables if they are empty. Since the script now should be called when changing pages it should be fixed too.

I will try to reproduce the other bug (inputs not committing on loosing focus) next. Regarding your error message with the main branch: Did you follow the steps from the `Development version` section of the README? Did you compile the JavaScript code (docker/native) or did you download it from the web server?

**Comment by MattTheCuber** [comment] 2024-06-06 17:55
I followed the compile instructions for native (`./build-docs.sh`).

Also, I just tested (rebuilt) and your fixes for the first two bugs worked.

**Comment by six-two** [comment] 2024-06-07 17:53
I reproduced the `ERROR   -  Unexpected field(s): apply_change_on_focus_change` bug and it should now be fixed.

That only leaves the input not saving values on focus change issue. I tried the same `mkdocs.yaml` config values (excluding some plugins) on the dev version, and it behaves as expected. And the code for textbox changes is pretty clear:
```javascript
        input_element.addEventListener("focusout", () => {
            // The value may change on the fly (use changes settings), so we can not just conditionally add the event listener, but need to check each time
            if (config.settings.apply_change_on_focus_change) {
                logger.debug("Textbox change confirmed by changing focus", placeholder.name, "- new value:", input_element.value);
                confirm_change();
            }
        })
```

What value do you get when you run `PlaceholderPlugin.settings.apply_change_on_focus_change` in the JS Console (part of the browser developer tools, F12 to open)? It should be `true`. I am thinking that you might be having something like the following in your `placeholder-plugin.yaml`:
```yaml
settings:
  apply_change_on_focus_change: false
```
That by definition disables the applying of values when you leave an input field (and would explain how you triggered the other bug).

If that does not fix your issue, could you please:
1. Post your `settings` section of `placeholder-plugin.yaml`
2. Check for any warning or error messages in the browser's console (Dev Tools)
3. Try it with a different browser

**Comment by MattTheCuber** [comment] 2024-06-07 18:18
I can confirm your fix for the `Unexpected field` error worked (after pulling and rebuilding)

`PlaceholderPlugin.settings.apply_change_on_focus_change` returned `false`. I ran `PlaceholderPlugin.settings.apply_change_on_focus_change = true` in the console, then tried editing and changing focus and that worked properly.

I do not have a settings section in `placeholder-plugin.yaml` (as I am fine with all defaults). I also tried adding the settings section with `apply_change_on_focus_change: true` and it still did not work. There are no warning or error messages in the console.

Good idea with the browser. Chrome has the bug, but Firefox does not.

**Comment by MattTheCuber** [comment] 2024-06-07 18:21
I can confirm the event would normally trigger in Chrome:

![image](https://github.com/six-two/mkdocs-placeholder-plugin/assets/32849887/5d69a4d4-ab33-427c-9a35-de46fdc00c05)

**Comment by six-two** [comment] 2024-06-07 18:23
Given what you wrote my suspicion is this: 
You clicked (disabled) the `Apply value when focus changes away` option, which persists itself in your localStorage and sets `apply_change_on_focus_change` to false.

![Screenshot 2024-06-07 at 20 21 29](https://github.com/six-two/mkdocs-placeholder-plugin/assets/20253663/9b28c331-3d71-4158-af70-7d0d36b862a2)

**Comment by MattTheCuber** [comment] 2024-06-07 18:26
That did it! Completely my bad, don't remember doing that!

**Comment by six-two** [comment] 2024-06-07 18:27
And since you hid the gears icon, you could not even find the setting again ;)

**Comment by MattTheCuber** [comment] 2024-06-07 18:29
Thank you!

**Comment by six-two** [comment] 2024-06-07 18:35
You're welcome! Since that should be all the issues you mentioned I will close this one. Should you find any more bugs just open another issue

**Closed by six-two** 2024-06-07 18:35 UTC

**Comment by MattTheCuber** [comment] 2024-06-07 18:41
No rush, just curious when you were expecting to release the next version?

**Comment by six-two** [comment] 2024-06-07 18:55
I hope to fix the remaining problem with the new inline editors (see #6) and plan to release version 0.5.0 afterwards. Might be a few days up to a couple of weeks. I try to avoid supporting multiple branches of the codebase, so I would like to prevent having to maintain an 0.4.x and back porting fixes to it

**Comment by MattTheCuber** [comment] 2024-06-07 18:56
Great, thanks!
